from tpl import *
C2=[]
C2.append(('case-energy','GreenEnergy - Vindkraftsservice','Optimering av underhall for vindkraftverk.',
co('Energi','200 turbiner, 60 anstallda','Vindkraftsparker i Norden','3000 larm/manad fran SCADA','Elsakerhetslagen, ISO 55001','SCADA-system, SAP PM, Salesforce Field Service, vader-API, GIS','Manga falsklarm fran sensorer. Felttekniker skickas pa onodiga besok.'),
'SCADA-sensordata, felkoder, textrapporter fran falttekniker, underhallshistorik, vaderdata.',
['Larm triggas i SCADA-systemet','Drifttekniker laser felkod och sensorvarden manuellt','Kontrollerar underhallshistorik i SAP PM','Bedomer om fysiskt besok kravs','Skapar arbetsorder i Salesforce Field Service','Falttekniker aker ut och rapporterar','Drifttekniker stanger arendet'],
[t1(['Tolka falttekniker-rapporter (fritext)','Korrelera felkoder med underhallshistorik','Bedoma om fysiskt besok kravs','Prioritera arenden efter risk'],['Troskellarning pa sensorvarden','Schemalagd underhallsrutin','Automatisk larmtriggning']),
t2('GreenEnergy far 3000 larm/manad varav manga ar falsklarm. Agenter kan automatiskt filtrera, korrelera med historik och prioritera. Detta minskar onodiga faltbesok med 40%.','Routing + Orchestrator-Worker','Larmen klassificeras forst (routing) och sedan orkestrerar en huvudagent specialistagenter for analys och atgardsforslag.','SCADA-larm -> [Agent 1: Felanalysagent]\\n  -> [Agent 2: Underhallsplanerare]\\n  -> [HITL: Drifttekniker] -> Godkann arbetsorder'),
t3([('Felanalysagent','Du ar specialist pa vindkraftsteknik och felanalys.','Analysera SCADA-larm och felkoder. Hamta underhallshistorik. Bedom om det ar akut, planerat eller falsklarm.',['Skriv pa svenska','Klassificera: akut/planerat/falsklarm','Motivera med historik och sensordata','Vid osaker bedomning: eskalera'],'FELANALYS\\nTurbin-ID: [id]\\nFelkod: [kod]\\nKategori: [akut/planerat/falsklarm]\\nHistorik: [tidigare fel]\\nRekommendation: [text]','Drifttekniker lagger 15 min pa att manuellt kolla varje larm mot historiken. Agenten gor detta pa sekunder.','SCADA-larmdata + felkod + turbin-ID','Felanalys med klassificering och rekommendation',['Funktionsanrop: hamta_underhallshistorik(turbin_id)'],['Lasakomst till SCADA och SAP PM','INGEN skrivratt']),
('Underhallsplanerare','Du ar underhallsplanerare for vindkraftverk.','Baserat pa felanalysen, skapa en atgardsplan med tidsestimat och resursbehov.',['Skriv pa svenska','Ange beraknad tid och antal tekniker','Prioritera efter risk och vader','Inkludera reservdelar om nodvandigt'],'ATGARDSPLAN\\nPrioritet: [hog/medel/lag]\\nAtgard: [beskrivning]\\nTid: [timmar]\\nTekniker: [antal]\\nReservdelar: [lista]','Att manuellt planera atgarder tar lang tid. Agenten foreslgar optimala atgarder baserat pa analys.','Felanalys + vaderprognos + teknikertillganglighet','Atgardsplan med resursbedomning',['Funktionsanrop: kolla_vader(plats, datum)'],['Lasakomst till vaderdata och resurskalender','INGEN bokningsmojlighet'])]),
t4('Felanalysagent','Underhallsplanerare',[('turbin_id','T-145'),('felkod','E-3201'),('kategori','planerat'),('historik','Liknande fel 2024-01 atgardad med byte av lager'),('risk','medel')],'Planeraren behover felkategori, historik och riskniva for att valja ratt atgard och resurser.'),
t5('hamta_underhallshistorik','Hamtar underhallshistorik for en turbin fran SAP PM.','turbin_id: str','dict med senaste_service, felhistorik, bytda_delar','Agenten behover historik for att bedoma om felet ar aterkommande och vilka delar som tidigare bytts.'),
t6([('Missad akut fel','Agent klassificerar akut som planerat. Atgard: Alla akuta larm dubbelkollas av drifttekniker.'),('Hallucination','Agent fabricerar underhallshistorik. Atgard: Validering mot SAP PM-data.'),('Vaderrisker','Tekniker skickas i daligttvader. Atgard: Automatisk vaderkontroll.')],'Drifttekniker godkanner alla arbetsordrar. Aldrig autonomt utskick av falttekniker.')]))

C2.append(('case-recruit','TechRecruit - CV-Matchning','Generativ AI for initial kandidatgallring.',
co('Rekrytering/HR-tech','25 anstallda, 1200 CV/manad inkommande','IT-bolag i Norden','15 min manuell gallring per CV','Diskrimineringslagen, GDPR','ATS (Teamtailor), LinkedIn Recruiter, Slack, Google Workspace','Rekryterare lagger majoriteten av sin tid pa att lasa oleampliga CV. Bara 10% av kandidaterna gar vidare.'),
'CV (PDF/Word), personligt brev, kravprofil fran kund med maste-krav och meriterande.',
['Kund skickar kravprofil via mejl','Rekryterare publicerar annons i ATS','CV strommer in till ATS','Rekryterare laser varje CV manuellt (15 min/CV)','Jamfor mot kravprofil','Skapar kortlista med 5-10 kandidater','Skickar kortlista till kund'],
[t1(['Tolka CV-innehall (ostrukturerade PDF:er)','Matcha kompetenser mot kravprofil semantiskt','Ranka kandidater efter lampligshet','Generera sammanfattning per kandidat'],['Filtrera pa formella krav (ar erfarenhet, certifikat)','Parsning av kontaktuppgifter','Automatisk bekraftelse till sokande']),
t2('TechRecruit hanterar 1200 CV/manad. Manuell gallring tar 15 min/CV = 300 timmar/manad. Agentifiering kan minska detta till 30 timmar och ge mer konsekvent bedomning.','Orchestrator-Worker + Evaluator','En orkestrerare fordelar CV till specialistagenter (parser + matchare) och en evaluator sakerstaller kvalitet.','CV inkommer -> [Agent 1: CV-Parser]\\n  -> [Agent 2: Matchningsagent]\\n  -> [Evaluator: Kvalitetskontroll]\\n  -> [HITL: Rekryterare] -> Godkann kortlista'),
t3([('CV-Parser','Du ar specialist pa att extrahera strukturerad data fran CV-dokument.','Extrahera: namn, erfarenhet, utbildning, kompetenser, sprak fran CV-dokument.',['Skriv pa svenska','Extrahera alla relevanta falt','Flagga otydliga eller saknade uppgifter','Var neutral - ingen vardering'],'CV-DATA\\nNamn: [namn]\\nErfarenhet: [ar]\\nKompetenser: [lista]\\nUtbildning: [lista]\\nSprak: [lista]','Rekryterare lagger tid pa att manuellt lasa och sammanfatta CV. Agenten extraherar data pa sekunder.','CV-fil (PDF/Word)','Strukturerad CV-data',['Funktionsanrop: extrahera_cv(fil_url)','OCR-tolkning av skannade CV'],['Lasakomst till ATS','INGEN modifiering av kandidatdata']),
('Matchningsagent','Du ar rekryteringsexpert som matchar kandidater mot kravprofiler.','Bedom hur val kandidaten matchar kravprofilen. Ge po ang och motivering.',['Skriv pa svenska','Poangsatt 0-100','Markera maste-krav: uppfyllt/ej uppfyllt','Var objektiv och evidensbaserad'],'MATCHRESULTAT\\nPoang: [0-100]\\nMaste-krav: [uppfyllt/ej]\\nMeriterande: [lista]\\nMotivering: [text]','Sakertstaller konsekvent och objektiv bedomning oberoende av rekryterarens erfarenhet.','CV-data + kravprofil','Matchresultat med poang och motivering',['Semantisk kompetensmatchning'],['Lasakomst till kravprofil','INGEN kontakt med kandidat'])]),
t4('CV-Parser','Matchningsagent',[('kandidat_id','K-456'),('namn','Anna Svensson'),('erfarenhet_ar','5'),('kompetenser','Python, AWS, Docker, Kubernetes'),('utbildning','MSc Datateknik KTH')],'Matchningsagenten behover strukturerad CV-data for att systematiskt jamfora mot kravprofilen.'),
t5('extrahera_cv','Extraherar text och struktur fran CV-dokument.','fil_url: str','dict med radata, sektioner, metadata','Agenten kan inte tolka CV utan att forst extrahera text. Verktyget hanterar bade PDF och Word-format.'),
t6([('Diskrimineringsbias','Agent nedvarderar CV fran vissa larosaten. Atgard: Regelbunden bias-audit. Anonymisera namn/alder.'),('GDPR','Personuppgifter i CV. Atgard: Automatisk radering efter 6 manader. Samtyckehantering.'),('Hallucination','Agent fabricerar kompetenser. Atgard: All output baseras pa extraherade falt, ej genererad text.')],'Rekryterare granskar ALLA kortlistor innan de skickas till kund. Ingen automatisk kontakt med kandidater.')]))

C2.append(('case-edu','EduLearn - Studentstod','Supervisory agent for inkommande studentfragor.',
co('EdTech/Utbildning','8000 studenter, 200 kurser','Distansstudenter i Norden','500 supportmeddelanden/dag, 48h svarstid','GDPR, Hogskoleforordningen','LMS (Canvas), Zendesk, Slack, FAQ-kunskapsbas, Ladok','Studenter far vanta for lange pa svar. Supportpersonal besvarar samma fragor om och om igen.'),
'Mejl/meddelanden fran studenter med fragor om schema, uppgifter, betyg och tekniska problem.',
['Student skickar fraga via Zendesk eller mejl','Supportpersonal laser meddelandet','Letar i FAQ/kunskapsbas efter svar','Om svaret inte finns: hor med kursansvarig larare','Skriver svar till studenten','Loggar arendet i Zendesk'],
[t1(['Tolka studentens fraga (fritext pa olika sprak)','Klassificera araendetyp (schema/uppgift/betyg/teknik)','Soka i kunskapsbas efter relevant svar','Generera anpassat svar'],['Automatisk bekraftelse till student','SLA-timer for svarstid','Routing till ratt kurs-kanal']),
t2('EduLearn far 500 meddelanden/dag med 48h svarstid. 60% av fragorna ar FAQ-fragor som kan besvaras automatiskt. Agentifiering minskar svarstid till under 5 min for vanliga fragor.','Routing + RAG (Retrieval-Augmented Generation)','Fragor maste dirigeras till ratt kategori (routing) och svar genereras fran kunskapsbas (RAG).','Studentfraga -> [Agent 1: Frageklassificerare]\\n  -> [Agent 2: Svarsagent (RAG)]\\n  -> [Evaluator: Tonkontroll]\\n  -> [HITL: Larare] (vid betygs-/undantagsfragor)'),
t3([('Frageklassificerare','Du ar en erfaren studentstodsperson.','Klassificera inkommande studentfraga. Bedom om den kan besvaras automatiskt eller kraver larare.',['Skriv pa svenska','Kategorier: schema/uppgift/betyg/teknik/ovrigt','Markera om HITL kravs (betyg/undantag/klagomal)','Identifiera relevant kurs'],'KLASSIFICERING\\nKategori: [typ]\\nKurs: [kurskod]\\nHITL: [ja/nej]\\nBradskande: [ja/nej]','Supportpersonal lagger tid pa att forst forsta fragan. Agenten klassificerar direkt och dirigerar ratt.','Ratt mejltext + studentinfo fran LMS','Klassificering med kategori och HITL-flagga',['Funktionsanrop: hamta_studentinfo(student_id)'],['Lasakomst till LMS och Zendesk','INGEN atkomst till betyg']),
('Svarsagent','Du ar en hjalpsam studentstodagent med tillgang till kursens kunskapsbas.','Generera svar pa studentens fraga baserat pa kunskapsbas. Svara ENBART med information fran kunskapsbasen.',['Skriv pa svenska','Svara ENBART med information fran kunskapsbas','Om svaret inte finns: eskalera','Var vanlig och professionell'],'SVAR TILL STUDENT\\n[svar baserat pa kunskapsbas]\\n\\nKalla: [referens till FAQ/kursinfo]','60% av fragorna ar FAQ-fragor. Agenten ger omedelbara svar utan att belasta larare.','Klassificering + studentfraga + kunskapsbas-treff','Formulerat svar med kallhanvisning',['Funktionsanrop: search_kunskapsbas(fraga, kurs_id)','RAG-sokning'],['Lasakomst till FAQ och kursinfo','INGEN betygshantering'])]),
t4('Frageklassificerare','Svarsagent',[('arende_id','ZD-5678'),('kategori','uppgift'),('kurs','DT2156'),('hitl','nej'),('studentfraga','Nar ar deadline for inlamning 3?')],'Svarsagenten behover kategori och kurs for att soka i ratt del av kunskapsbasen.'),
t5('search_kunskapsbas','Soker i kursens FAQ och kunskapsbas.','fraga: str, kurs_id: str','dict med resultat, relevans_score, kalla','Agenten maste kunna soka i kunskapsbasen for att svara korrekt. Utan RAG riskerar agenten att hallucienera svar.'),
t6([('Felaktigt svar','Agent ger fel information om deadline/betyg. Atgard: Enbart svar fran kunskapsbas (RAG). Aldrig genererade fakta.'),('Eskaleringsmiss','Agent missar att studenten behover manniska. Atgard: Alla betygs/undantagsfragor till HITL.'),('GDPR','Studentuppgifter. Atgard: Minimal datadelning, loggar raderas efter termin.')],'Larare godkanner alla betygsrelaterade svar och undantagsbeslut. Automatiserade svar enbart for FAQ.')]))

C2.append(('case-food','FoodSafe - Livsmedelskontroll','Analys av inspektionsrapporter fran restauranger.',
co('Myndighet/Livsmedel','120 inspektorer, regional myndighet','Restauranger, catering, livsmedelsbutiker','15 000 inspektioner/ar','Livsmedelslagen, EU-forordning 852/2004','Inspektionssystem, Diarium, GIS, bildanalys-API','Inkonsekvent riskbedomning mellan inspektorer. Allvarliga avvikelser missas ibland.'),
'Granskningsprotokoll (fritext), foton pa avvikelser, tidigare inspektionshistorik, verksamhetsdata.',
['Inspektor genomfor platsbesok','Skriver fritext-anteckningar pa surfplatta','Tar foton pa avvikelser','Aterkommet till kontoret: skriver formell rapport','Bedomer riskniva manuellt','Fattar beslut om atgard (forelaggande/ominspektion/godkant)','Registrerar i diariet'],
[t1(['Tolka inspektorers fritextanteckningar','Analysera foton pa avvikelser (bildanalys)','Jamfora mot tidigare inspektionshistorik','Bedoma riskniva konsekvent'],['Schemalagda inspektioner','Registrering i diariet','Automatisk paminnelse for ominspektion']),
t2('FoodSafe genomfor 15 000 inspektioner/ar med inkonsekvent riskbedomning. Agenter kan standardisera bedomningen och identifiera allvarliga avvikelser snabbare.','Orchestrator-Worker','En orkestrerare fordelar arbetet till specialistagenter (textanalys + bildanalys) och sammanstaller resultatet.','Inspektionsdata -> [Agent 1: Rapportanalys]\\n  -> [Agent 2: Riskbedomare]\\n  -> [HITL: Inspektor] -> Signera beslut'),
t3([('Rapportanalysagent','Du ar expert pa livsmedelshygien och inspektionsrapporter.','Analysera inspektorens anteckningar och identifiera avvikelser. Klassificera varje avvikelse.',['Skriv pa svenska','Klassificera: kritisk/stor/mindre avvikelse','Referera till relevant lagparagraf','Flagga aterkommande problem'],'AVVIKELSEANALYS\\nVerksamhet: [namn]\\nAvvikelser: [lista med klassificering]\\nHistorik: [tidigare problem]\\nReferens: [lagparagraf]','Inspektorer tolkar avvikelser olika. Agenten ger konsekvent klassificering mot lagtext.','Fritextanteckningar + foton + verksamhets-ID','Klassificerade avvikelser med lagreferenser',['Funktionsanrop: hamta_inspektionshistorik(verksamhets_id)','Bildanalys: analysera_foto(bild_url)'],['Lasakomst till inspektionssystem och lagdatabas','INGEN beslutsbefogenhet']),
('Riskbedomare','Du ar riskbedomare for livsmedelssakerahet.','Baserat pa avvikelseanalysen, ge en overgripande riskbedomning och foreslga atgard.',['Skriv pa svenska','Riskniva: hog/medel/lag','Foreslga: forelaggande/ominspektion/godkant','Vid hog risk: flagga som akut'],'RISKBEDOMNING\\nRiskniva: [hog/medel/lag]\\nForeslagna atgard: [typ]\\nMotivering: [text]\\nOminspektion: [datum]','Standardiserar riskbedomning over alla inspektorer. Minskar risken for att allvarliga problem missas.','Avvikelseanalys + verksamhetshistorik','Riskbedomning med atgardsforslag',['Jamforelseanalys mot liknande verksamheter'],['Lasakomst till historik','INGEN myndighetsbeslut'])]),
t4('Rapportanalysagent','Riskbedomare',[('verksamhets_id','V-890'),('avvikelser','[kritisk: temperatur kylrum 12C, mindre: skadat golv]'),('tidigare_anmarkningar','2'),('senaste_inspektion','2024-06-15')],'Riskbedomaren behover klassificerade avvikelser med historik for att bedoma korrekt riskniva.'),
t5('hamta_inspektionshistorik','Hamtar tidigare inspektioner for en verksamhet.','verksamhets_id: str','dict med antal_inspektioner, avvikelsehistorik, senaste_beslut','Agenten behover historiken for att bedoma om avvikelser ar aterkommande, vilket hojer risknivan.'),
t6([('Missad halsoorisk','Agent klassificerar allvarlig avvikelse som lag risk. Atgard: Alla hogriskarender till HITL.'),('Bias','Systematisk underbedomning av vissa verksamhetstyper. Atgard: Regelbunden kalibrering.'),('Myndighetsansvar','Agenten far ALDRIG fatta myndighetsbeslut. Atgard: Inspektoren signerar alltid.')],'Inspektor signerar ALLA atgardsforelagganden. Myndighetsbeslut kraver manniska enligt lag.')]))
