from tpl import *
C3=[]
C3.append(('case-media','MediaHouse - Moderering','Hybridflode for innehallsmoderering av kommentarer.',
co('Media/Nyheter','500 anstallda, 2M lasare/dag','Nyhetskonsumenter i Sverige','200 000 kommentarer/dag','Yttrandefrihetsgrundlagen, PUL/GDPR','CMS (WordPress VIP), moderationsverktyg, NLP-pipeline, anvandarhistorik-DB','Balans mellan yttrandefrihet och trygghet. Moderatorer hinner inte granska allt.'),
'Anvandarkommentarer, anmalningsorsak, anvandarhistorik, artikelkontext.',
['Kommentar publiceras pa artikel','Automatiskt ordfilter flaggar eventuellt','Moderator laser flaggade kommentarer','Bedomer om kommentaren bryter mot policy','Tar bort eller godkanner','Hanterar overklaganden'],
[t1(['Tolka kommentarens kontext och ton','Bedoma om kommentar ar hatretorik, desinformation eller satir','Analysera anvandarens historik','Hantera grazon-fall'],['Ordfilter (blocklista)','Spamdetektering (lankar, upprepning)','Automatisk borttagning av uppenbart olagligt innehall']),
t2('MediaHouse far 200 000 kommentarer/dag. Moderatorer hinner granska 5%. Agenter kan forgranska 95% och eskalera enbart grazon-fall. Minskar exponering for skadligt innehall for moderatorer.','Routing + Evaluator-Optimizer','Kommentarer dirigeras baserat pa riskniva (routing). Grazon-fall utvärderas av evaluator som kan skicka tillbaka for ombedomning.','Kommentar -> [Regelmotor: Ordfilter]\\n  -> [Agent 1: Kontextanalysagent]\\n  -> [Agent 2: Policybedomare]\\n  -> [HITL: Moderator] (vid grazon 50-90% konfidens)'),
t3([('Kontextanalysagent','Du ar expert pa sprakanalys och kontext i kommentarsfalt.','Analysera kommentarens innehall i relation till artikeln. Bedom ton, avsikt och eventuella regelbrott.',['Skriv pa svenska','Bedom: godkant/grazon/ta_bort','Ange konfidensniva 0-100%','Ta hansyn till ironi, satir och kontext'],'KOMMENTARSANALYS\\nKommentar-ID: [id]\\nBedomning: [godkant/grazon/ta_bort]\\nKonfidens: [0-100%]\\nOrsak: [text]','Moderatorer kan inte lasa 200 000 kommentarer. Agenten filtrerar och eskalerar enbart problematiska fall.','Kommentarstext + artikelrubrik + anvandarhistorik','Bedomning med konfidens och orsak',['Semantisk textanalys','Kontextforstaelse'],['Lasakomst till kommentarer och artiklar','INGEN publiceringskontroll']),
('Policybedomare','Du ar policyexpert for medieverksamhet.','Bedom om kommentaren bryter mot MediaHouse publiceringsregler. Ge rekommendation.',['Skriv pa svenska','Ta hansyn till yttrandefrihet','Referera till specifik policyregel','Vid osakerhet: eskalera till HITL'],'POLICYBEDOMNING\\nRegel: [vilken policy]\\nBeslut: [godkann/ta_bort/eskalera]\\nMotivering: [text]','Sakertstaller att publiceringspolicy tillampas konsekvent oavsett moderator.','Kommentarsanalys + publiceringsregler','Policybedomning med regelreferens',['Funktionsanrop: hamta_publiceringsregler(kategori)'],['Lasakomst till policyregelverk','INGEN moderationsbefogenhet'])]),
t4('Kontextanalysagent','Policybedomare',[('kommentar_id','C-12345'),('bedomning','grazon'),('konfidens','0.72'),('orsak','Mojlig hatretorik men kan vara satir'),('artikel_amne','invandring')],'Policybedomaren behover kontextanalys och artikelamne for att tillämpa ratt policyregler.'),
t5('hamta_publiceringsregler','Hamtar relevanta publiceringspolicyer for en kategori.','kategori: str','dict med regler, undantag, eskaleringsregler','Agenten maste kunna referera till exakta policyregler for att motivera beslut. Utan detta riskerar godtyckliga bedomningar.'),
t6([('Overcensur','Agent tar bort legitima asikter. Atgard: Alla grazon-fall till moderator.'),('Undercensur','Agent missar hatretorik. Atgard: Stickprov pa godkanda kommentarer.'),('Yttrandefrihet','Juridisk risk vid felaktig censur. Atgard: Tydlig dokumentation av varje beslut.')],'Moderator granskar alla grazon-arenden (konfidens 50-90%). Agent far enbart ta bort uppenbara policybrott (>95% konfidens).')]))

C3.append(('case-property','PropertyCare - Felanmalan','Automatiserad hantering av hyresgasters felanmalningar.',
co('Fastighetsforvaltning','45 anstallda, 12 000 lagenheter','Hyresgaster i Stor-Stockholm','800 felanmalningar/manad','Hyreslagen, Jordabalken, GDPR','Fastighetssystem (Vitec), Jira Service Management, SMS-gateway, entreprenorsportal','Felklassificering av akuta arenden. Hyresgaster klagar pa lang svarstid.'),
'Fritext i webformular, foton pa skadan, adress, hyresgasthistorik fran fastighetssystem.',
['Hyresgast skickar felanmalan via app/webb','Kundtjanst laser anmalan och bedomer prioritet','Letar efter liknande arenden i systemet','Klassificerar typ (VVS/el/bygg/utomhus)','Kontaktar ratt entreprenor','Bokar tid med hyresgast','Foljer upp att jobb ar utfort'],
[t1(['Tolka hyresgastens fritextbeskrivning','Analysera foton for att identifiera skadetyp','Bedoma allvarlighetsgrad/bradska','Matcha mot ratt entreprenor'],['Automatisk bekraftelse-SMS till hyresgast','SLA-timer for responstid per kategori','Schemalagda underhallsplaner']),
t2('PropertyCare far 800 felanmalningar/manad. Felklassificering gor att akuta arenden (vattenlacka) ibland hamnar i vanlig ko. Agentifiering sakerstaller att akuta arenden prioriteras korrekt.','Routing + Orchestrator-Worker','Felanmalningen dirigeras till ratt kategori (routing) och en orkestrerare fordelar uppgifter till specialistagenter.','Felanmalan -> [Agent 1: Arendeklassificerare]\\n  -> [Agent 2: Prioriteringsagent]\\n  -> [HITL: Fastighetsskotare] (vid akut)\\n  -> Automatisk entreprenorsbokning (vid rutin)'),
t3([('Arendeklassificerare','Du ar fastighetsexpert som klassificerar felanmalningar.','Analysera felanmalans text och eventuella foton. Klassificera typ och identifiera adress.',['Skriv pa svenska','Kategorier: VVS/el/bygg/utomhus/ovrigt','Identifiera lagenhets-ID fran adress','Flagga potentiellt akuta arenden (vatten, brand)'],'ARENDEKLASSIFICERING\\nArende-ID: [id]\\nKategori: [VVS/el/bygg/utomhus]\\nLagenhet: [id]\\nBeskrivning: [sammanfattning]\\nAkut: [ja/nej]','Kundtjanst lagger tid pa att tolka och klassificera. Agenten gor detta instant med bildanalys.','Fritextbekrivning + foton + hyresgast-ID','Klassificering med kategori och akut-flagga',['Funktionsanrop: analysera_bild(bild_url)','Adressmatchning mot fastighetsregister'],['Lasakomst till fastighetssystem','INGEN bokningsmojlighet']),
('Prioriteringsagent','Du ar prioriteringsexpert for fastighetsunderhall.','Baserat pa klassificering och historik, satt prioritet och foreslga atgard.',['Skriv pa svenska','Prioritet: akut(4h)/hog(24h)/normal(5dagar)/lag(planerat)','Matcha med ratt entreprenor','Vid vattenlacka/brand: eskalera direkt'],'PRIORITERING\\nPrioritet: [akut/hog/normal/lag]\\nSLA: [svarstid]\\nEntreprenor: [forslag]\\nAtgard: [text]','Sakertstaller att akuta arenden (vattenlacka, stromavbrott) aldrig hamnar i vanlig ko.','Klassificering + felanmalningshistorik + entreprenorsregister','Prioritering med SLA och entreprenorsforslag',['Funktionsanrop: sok_entreprenor(kategori, omrade)'],['Lasakomst till entreprenorsregister','INGEN avtalsingaende'])]),
t4('Arendeklassificerare','Prioriteringsagent',[('arende_id','FA-2024-567'),('kategori','VVS'),('lagenhet','L-4523'),('beskrivning','Vattenlacka under diskbanken'),('akut','ja'),('foton','2 bilder')],'Prioriteringsagenten behover kategori och akut-flagga for att satta ratt SLA och matcha entreprenor.'),
t5('analysera_bild','Analyserar foto fran felanmalan for att identifiera skadetyp.','bild_url: str','dict med skadetyp, allvarlighetsgrad, identifierade_objekt','Hyresgasters textbeskrivningar ar ofta vaga. Bildanalys ger objektiv information om skadens omfattning.'),
t6([('Felklassificering','Agent bedomer vattenlacka som lagprio. Atgard: Alla VVS-arenden med nyckelord vatten/lacka far automatisk akut-flagga.'),('Hallucination','Agent fabricerar entreprenorsforslag. Atgard: Validering mot entreprenorsregistret.'),('Integritet','Foton kan innehalla personlig info. Atgard: Foton raderas efter arendet stangts.')],'Fastighetsskotare godkanner alla akuta arenden och arbetsordrar over 5000 kr.')]))

C3.append(('case-legal','LegalAssist - Avtalsgranskning','Agent for identifiering av riskfyllda klausuler.',
co('Juridik/Advokatbyra','45 jurister, 15 administratorer','Foretag i Norden','200 avtal/manad, 4h/avtal manuell granskning','Advokatsekretess, GDPR, Avtalslagen','DMS (iManage), avtalssystem (Precisely), CRM, Teams, intern policydatabas','Granskning tar for lang tid. Risk att riskfyllda klausuler missas vid tidsbrist.'),
'PDF-avtal pa 10-50 sidor, checklista over riskparametrar, tidigare avtalsbedomningar fran policydatabas.',
['Klient skickar avtal via mejl/Teams','Jurist laser avtalet (10-50 sidor) manuellt','Jamfor varje klausul mot checklista och policy','Markerar riskfyllda klausuler','Skriver PM med rekommendationer','Senior jurist granskar PM','Skickar aterkoppling till klient'],
[t1(['Tolka juridisk text pa svenska och engelska','Identifiera riskfyllda klausuler semantiskt','Jamfora klausuler mot intern policydatabas','Generera strukturerat PM'],['Dokumentparsning (PDF till text)','Versionskontroll av avtal','Deadlinebevakning for avtalstider']),
t2('LegalAssist granskar 200 avtal/manad a 4h = 800 timmar/manad. Agentifiering kan minska granskningstiden till 1h/avtal genom att automatisera initial klausulidentifiering. Juristen fokuserar pa bedomning istallet for lasning.','Orchestrator-Worker + Evaluator-Optimizer','En orkestrerare fordelar avtalet till specialistagenter. En evaluator (Critic-agent) sakerstaller kvalitet genom att granska agenternas output.','Avtal-PDF -> [Agent 1: Avtalstolkare]\\n  -> [Agent 2: Klausulgranskare]\\n  -> [Critic: Kvalitetskontroll]\\n  -> REVIDERA/GODKANT\\n  -> [HITL: Jurist] -> Signera PM'),
t3([('Avtalstolkare','Du ar specialist pa att extrahera och strukturera information fran avtalsdokument.','Extrahera nyckelklausuler fran avtalet: parter, lopstid, ansvar, uppsagning, force majeure, vitesklausuler.',['Skriv pa svenska','Extrahera ALLA klausuler, missa inga','Markera klausuler som avviker fran standard','Ange sidnummer for varje klausul'],'AVTALSEXTRAKT\\nParter: [namn]\\nLoptid: [datum]\\nKlausuler:\\n- [klausul 1, sida X]\\n- [klausul 2, sida Y]\\nAvvikelser: [lista]','Jurister lagger 2h+ pa att lasa och sammanfatta avtal. Agenten extraherar strukturerad data pa minuter.','Avtal-PDF (ratext)','Strukturerat avtalsextrakt med alla klausuler och sidnummer',['Funktionsanrop: extrahera_pdf(dokument_url)','Juridisk terminologi-igenkanning'],['Lasakomst till DMS (iManage)','INGEN klientkontakt']),
('Klausulgranskare','Du ar riskbedomare for avtalsklausuler.','Jamfor varje klausul mot intern riskpolicy och checklista. Identifiera risker och ge rekommendation.',['Skriv pa svenska','Riskklasser: hog/medel/lag','Referera till intern policyregel','Foreslga alternativ formulering vid hog risk'],'RISKANALYS\\nKlausul: [text]\\nRisk: [hog/medel/lag]\\nPolicyreferens: [regel]\\nRekommendation: [text]\\nAlternativ formulering: [forslag]','Sakertstaller att alla klausuler granskas mot policy. Minskar risken for missade riskklausuler.','Avtalsextrakt + riskchecklista + policydatabas','Riskanalys per klausul med rekommendation',['Funktionsanrop: sok_policy(klausultyp)','Jamforelse mot standardavtal'],['Lasakomst till policydatabas','INGEN avtalsbeslut'])]),
t4('Avtalstolkare','Klausulgranskare',[('avtal_id','AVT-2024-156'),('parter','TechCorp AB / NordicCloud AB'),('klausuler','[ansvarsbegransning s.12, vitesklausul s.15, uppsagning s.18]'),('avvikelser','Vitesklausul avviker fran standard')],'Klausulgranskaren behover strukturerade klausuler med sidnummer for att systematiskt jamfora mot policy.'),
t5('sok_policy','Soker i intern policydatabas efter relevant riskpolicy.','klausultyp: str','dict med regelverk, grans, undantag, prejudikat','Agenten maste referera till exakt intern policy for att ge ratt rekommendation. Fri tolkning ar inte acceptabelt.'),
t6([('Missad riskklausul','Agent missar kritisk klausul. Atgard: Critic-agent dubbelgranskar. Jurist signerar alltid.'),('Hallucination','Agent fabricerar policyregler. Atgard: ALL output valideras mot policydatabasen.'),('Advokatsekretess','Klientdata passerar agenter. Atgard: All bearbetning sker on-premise, ej i molntjanst.'),('Oandlig loop','Critic underkanner upprepade ganger. Atgard: Max 2 revisioner, sedan eskalering.')],'Jurist signerar ALLA PM innan de skickas till klient. Advokatsekretessen kraver att inga agenter kommunicerar externt.')]))
