from tpl import *
C=[]
C.append(('case-tech','HealthTrack Nordic AB','Optimera larmhantering fran barbara hjartmonitorer.',
co('E-halsa/MedTech','120 anstallda, 30 000 anvandare','Patienter via vardgivare','2000+ larm/dag, 85% falsklarm','GDPR, MDR, Patientdatalagen','AWS IoT Core, FHIR-baserat EHR, PostgreSQL, Grafana, PagerDuty','Sjukskoterskor drunknar i falsklarm. Kritiska larm riskerar att missas.'),
'EKG-sensordata, pulsvarden, syremattnad, patientrapporterade symptom (fritext), journalhistorik.',
['Larm triggas av troskelvarde i IoT-plattformen','Sjukskoterska ser larmet i dashboard och laser sensordata','Kontrollerar patientens journal manuellt','Bedomer om larmet kraver atgard eller ar falsklarm','Vid verkligt larm: kontaktar patient per telefon','Dokumenterar bedomning i journalsystemet'],
[t1(['Tolka fritextbeskrivningar av symptom','Korrelera EKG-monster med patienthistorik','Bedoma allvarlighetsgrad fran multipla signaler','Generera klinisk sammanfattning'],['Troskelvarden (puls >120/<40, SpO2 <90%)','SLA-timer for responstid','Notifieringsregler till PagerDuty']),
t2('HealthTrack hanterar 2000+ larm/dag varav 85% falsklarm. Genom att agentifiera klassificering och klinisk analys kan sjukskoterskor fokusera pa verkliga larm. Ledtiden minskar fran 15 min till under 2 min.','Routing + Evaluator-Optimizer','Larmen maste forst klassificeras (routing) och sedan kvalitetssakras (evaluator kontrollerar bedomningen innan HITL).','Sensor-data -> [Regelmotor: Troskelvarden]\\n  -> [Agent 1: Larmklassificerare]\\n  -> [Agent 2: Klinisk Analysagent]\\n  -> [Evaluator: Kvalitetskontroll]\\n  -> [HITL: Sjukskoterska] -> Patientkontakt'),
t3([('Larmklassificerare','Du ar specialist pa medicinsk signalanalys och klassificering av hjartlarm.','Analysera inkommande larmdata. Hamta patienthistorik via verktyg. Klassificera larmet.',['Skriv pa svenska','Klassificera som: kritiskt/warning/info','Ange konfidens 0-100%','Falsklarm ska motiveras'],'LARMKLASSIFICERING\\nLarm-ID: [id]\\nKategori: [kritiskt/warning/info]\\nKonfidens: [0-100%]\\nMotivering: [2-3 meningar]','I det manuella flodet granskar sjukskoterskan varje larm. Med 2000+/dag missas kritiska larm. Agenten filtrerar automatiskt.','Ra sensordata (EKG, puls, SpO2) + larm-ID','Klassificering med kategori, konfidens och motivering',['Funktionsanrop: hamta_patienthistorik(patient_id)','Monsterigenkanning i EKG-data'],['Lasakomst till EHR (journal)','INGEN skrivrakomst']),
('Klinisk Analysagent','Du ar klinisk radgivare som bedomer larm baserat pa patientkontext.','Baserat pa larmklassificering och patienthistorik, ge en klinisk rekommendation.',['Skriv pa svenska','Rekommendera: kontakta_patient/bevaka/ignorera','Motivera med klinisk evidens','Vid osakerhet: eskalera till HITL'],'KLINISK BEDOMNING\\nRekommendation: [atgard]\\nMotivering: [klinisk grund]\\nBradskande: [ja/nej]','Sjukskoterskan behover beslutsstod for att korrelera larmdata med medicinlista och diagnoshistorik.','Larmklassificering + patienthistorik + medicinlista','Klinisk rekommendation med motivering',['Korrelera larmdata med kanda diagnoser','Identifiera lakemedelsinteraktioner'],['Lasakomst till journal och medicinlista','INGEN ordinationsratt'])]),
t4('Larmklassificerare','Klinisk Analysagent',[('larm_id','LRM-2024-1547'),('kategori','potentiell_arytmi'),('konfidens','0.87'),('ekg_sammanfattning','Irreguljar RR-intervall'),('patient_id','P-12345')],'Analysagenten behover klassificeringen och patient-ID for att hamta ratt journaldata och gora kontextuell bedomning.'),
t5('hamta_patienthistorik','Hamtar patientens journaldata fran EHR-systemet.','patient_id: str','dict med diagnoser, mediciner, allergier, senaste_besok','Agenten behover patientkontext for att bedoma om ett larmmonstrer ar nytt eller kant sedan tidigare.'),
t6([('Falskt negativ','Agent missar kritiskt larm. Atgard: Alla larm med konfidens under 95% gar till HITL.'),('Hallucination','Agent fabricerar klinisk info. Atgard: Korsvalidering mot regelmotor.'),('GDPR/Patientdata','Kanslig halsodata. Atgard: All data stannar inom EU, krypterad.'),('Oandlig loop','Evaluator underkanner. Atgard: Max 2 iterationer, sedan manniska.')],'Sjukskoterska godkanner ALLA atgarder som innebar patientkontakt.')]))

C.append(('case-fleet','FleetOps Logistics AB','AI-agentifiering av omdirigering vid forseningar.',
co('Transport/Logistik','500 lastbilar, 85 anstallda','Dagligvarukedjor och e-handel','40 forseningar/dag','Transportavtal/SLA, ADR','TMS, Google Maps API, SAP, Salesforce CRM, vaderdata-API','Transportledare hinner inte omdirigera i tid. SLA-brott kostar 50k+/manad.'),
'Ruttdata, vaderrapporter, ETA-krav, trafikinfo, SLA-avtal, fordonspositioner.',
['Fordonssensor triggar forsening (GPS stillastaende >30 min)','Transportledare ser larmet i TMS','Ringer chaufforen for att forsta orsaken','Kontrollerar manuellt om alternativ rutt finns','Kontaktar kund om ny ETA','Uppdaterar rutt i TMS','Loggar forseningen i SAP'],
[t1(['Tolka chaufforens fritextrapport','Bedoma vilken kund som paverkas mest (SLA-risk)','Foreslga alternativ rutt','Generera kundkommunikation'],['GPS-sparning och ETA-berakning','SLA-kontroll mot avtal','Automatisk larmtriggning vid forsening']),
t2('FleetOps hanterar 40 forseningar/dag. Manuell omplanering tar 20-30 min/arende. Agentifiering minskar responstid till under 5 min och forebygger SLA-brott.','Routing + Parallelization','Flera datakallor (vader, trafik, kundkrav) analyseras parallellt, sedan dirigeras arendet baserat pa typ.','Forseningslarm -> [Parallell: Vaderagent + Trafikagent]\\n  -> [Router: Beslutspunkt]\\n  -> [Agent: Ruttoptimerare]\\n  -> [HITL: Transportledare] -> Godkann ny rutt'),
t3([('Forseningsklassificerare','Du ar logistikexpert som klassificerar transportforseningar.','Analysera forseningsdata och klassificera orsak. Bedom SLA-paverkan.',['Skriv pa svenska','Klassificera orsak: vader/trafik/tekniskt/olycka','Prioritera efter SLA-risk: hog/medel/lag','Ange beraknad forsening i minuter'],'FORSENINGSRAPPORT\\nFordons-ID: [id]\\nOrsak: [kategori]\\nBeraknad forsening: [min]\\nSLA-risk: [hog/medel/lag]','Transportledaren maste idag ringa chaufforen och bedoma manuellt. Agenten automatiserar klassificering och SLA-kontroll.','GPS-data, chaufforrapport, vaderdata','Forseningsrapport med orsak och SLA-risk',['Funktionsanrop: check_sla(kund_id, ny_eta)'],['Lasakomst till TMS och SLA-databas']),
('Ruttoptimerare','Du ar ruttplanerare som hittar alternativa leveransrutter.','Foreslga optimal alternativ rutt som minimerar forsening.',['Skriv pa svenska','Ge max 2 ruttalternativ','Visa tid- och kostnadsskillnad','Beakta fordonstyp'],'RUTTALTERNATIV\\nAlt 1: [rutt, tid, kostnad]\\nAlt 2: [rutt]\\nRekommendation: [val]','Manuell ruttplanering tar 20+ min. Agenten ger rekommendation pa sekunder.','Forseningsrapport + trafikdata + fordonsposition','Ruttalternativ med tid/kostnadsanalys',['Funktionsanrop: hamta_alternativ_rutt(fran, till, typ)'],['Lasakomst till Google Maps API','INGEN bokningsmojlighet'])]),
t4('Forseningsklassificerare','Ruttoptimerare',[('fordons_id','FO-234'),('orsak','vader_halka'),('position','59.33,18.07'),('beraknad_forsening_min','45'),('kund_id','K-789'),('sla_deadline','2024-01-15T14:00')],'Ruttoptimeraren behover position, orsak och SLA-deadline for att berakna basta alternativa rutt.'),
t5('check_sla','Kontrollerar om ny ETA bryter kundens SLA-avtal.','kund_id: str, ny_eta: datetime','dict med sla_status, marginal_minuter, konsekvens','Agenten maste veta om forseningen bryter SLA innan resurser laggs pa omdirigering.'),
t6([('Felaktig omdirigering','Agent valjer langre rutt. Atgard: Transportledare godkanner alla andringar.'),('Hallucination','Agent fabricerar vagdata. Atgard: Validering mot Maps API.'),('Systemkoppling','TMS/GPS nere. Atgard: Fallback till manuell process.')],'Transportledare godkanner alla ruttforandringar som paverkar SLA.')]))

C.append(('case-bank','NordicBank - Kredithantering','Automation av lanebedomningar for privatlan.',
co('Finans','300 anstallda, mellanstor nischbank','Privatpersoner i Sverige','800 ansokningar/vecka, 5-7 dagars handlaggningstid','KYC, PSD2, Banklagen, GDPR, Konsumentkreditlagen','UC (kreditupplysning), BankID, Core Banking (Temenos), Bisnode, intern policymatris','Lang handlaggningstid. Inkonsekvent bedomning. Riskflaggor missas i lonespecar.'),
'Laneansokningar, kreditupplysning (UC), lonespecifikation (PDF), kontoutdrag, policymatris.',
['Kund skickar ansokan via webbformular','Handlaggare laser ansokan och bestammer lanetyp','Bestaller kreditupplysning fran UC manuellt','Laser lonespec (PDF) och beraknar skuldkvot','Jamfor mot intern policymatris','Skriver beslutsunderlag','Chef godkanner eller avslar'],
[t1(['Tolka lonespec-PDF (ostrukturerad data)','Analysera kontoutdrag for utgiftsmonster','Sammanfatta riskprofil fran multipla kallor','Generera beslutsunderlag'],['Kreditupplysning via UC API','Berakna skuldkvot','BankID-verifiering','Lagstadgade grans']),
t2('NordicBank hanterar 800 ansokningar/vecka med 5-7 dagars handlaggningstid. Agentifiering minskar till 1-2 dagar med konsekvent bedomning oavsett handlaggare.','Hybrid (regelmotor + agenter + HITL)','Blandar strikt regelstyrda steg (kreditupplysning, skuldkvot) med tolkningssteg (analysera lonespec). HITL ar lagstadgat krav.','Ansokan -> [Agent 1: Dokumenttolkare]\\n  -> kreditupplysning_api() [Regelmotor]\\n  -> berakna_skuldkvot() [Regelmotor]\\n  -> [Agent 2: Riskbedomare]\\n  -> [Agent 3: Sammanfattare]\\n  -> [HITL: Kredithandlaggare] -> Godkann/Avsla'),
t3([('Dokumenttolkare','Du ar specialist pa att tolka svenska finansiella dokument.','Extrahera nyckeldata fran lonespec-PDF: bruttoinkomst, nettoinkomst, arbetsgivare, anstallningsform.',['Skriv pa svenska','Extrahera: brutto, netto, arbetsgivare, anstallningsform','Flagga om dokumentet verkar manipulerat','Ange konfidens per falt'],'LONEDATA\\nBruttoinkomst: [belopp]\\nNettoinkomst: [belopp]\\nArbetsgivare: [namn]\\nAnstallningsform: [tillsvidare/visstid]\\nKonfidens: [0-100%]','Handlaggare lagger 10-15 min pa varje lonespec. Agenten extraherar data pa sekunder.','Lonespec-PDF','Strukturerad lonedata med konfidens',['Funktionsanrop: extrahera_pdf(dokument_url)','OCR-tolkning'],['Lasakomst till dokumentarkiv','INGEN skrivratt']),
('Riskbedomare','Du ar kreditanalytiker som bedomer lanerisk.','Baserat pa lonedata, kreditupplysning och skuldkvot, ge en riskbedomning.',['Skriv pa svenska','Riskklasser: lag/medel/hog/avsla','Motivera med datapunkter','Identifiera riskflaggor'],'RISKBEDOMNING\\nRiskklass: [lag/medel/hog/avsla]\\nSkuldkvot: [%]\\nFlaggor: [lista]\\nRekommendation: [text]','Sakertstaller konsekvent bedomning. Minskar risken for missade flaggor.','Lonedata + kreditupplysning + skuldkvot + policymatris','Riskbedomning med riskklass och rekommendation',['Funktionsanrop: hamta_kreditupplysning(personnr)'],['Lasakomst till UC och policymatris','INGEN beslutsfatta'])]),
t4('Dokumenttolkare','Riskbedomare',[('ansokan_id','LA-2024-892'),('bruttoinkomst','42000'),('nettoinkomst','31500'),('arbetsgivare','Volvo AB'),('anstallningsform','tillsvidare'),('konfidens','0.95')],'Riskbedomaren behover lonedata for att berakna skuldkvot och jamfora mot policymatris.'),
t5('hamta_kreditupplysning','Hamtar kreditupplysning fran UC.','personnr: str','dict med skuldsaldo, betalningsanmarkningar, score','Agenten kan inte bedoma kreditvardighet utan extern kreditdata. UC ar lagstadgat krav.'),
t6([('Felaktig bedomning','Agent missar riskflaggor. Atgard: Alla bedomningar granskas av handlaggare.'),('Bias','Systematisk bias. Atgard: Regelbunden A/B-testning och bias-audit.'),('GDPR','Personnummer och finansdata. Atgard: Dataminimering, kryptering.'),('Manipulerad PDF','Forfalskad lonespec. Atgard: Korsvalidering mot UC-data.')],'Kredithandlaggare godkanner ALLA lanebeslut. Lagstadgat krav.')]))
